### ISSUE TITLE
Pyproj vs Rasterio conflict

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/stac-vrt#8]
Hi @TomAugspurger,

This project looks great. I just wanted to point out that both Pyproj and Rasterio, if built from wheels can be shipped with completely different version of GDAL/PROJ. I personally try to avoid using both at the same time, especially because Rasterio can do almost all basic operation (reprojection of geometry, CRS operations ...).

ref: https://github.com/developmentseed/morecantile/issues/26#issuecomment-638231122

This is just a personal opinion ;-)

**Comment by kylebarron** [comment]
From a cursory look at the code it looks like pyproj isn't needed. Instead of `pyproj.crs.CRS` you should be able to use `rasterio.crs.CRS` instead
```py
In [1]: import rasterio

In [2]: rasterio.crs.CRS.from_epsg(4326)
Out[2]: CRS.from_epsg(4326)
```

**Comment by TomAugspurger** [comment]
Thanks (I'm new to geospatial, so expect many of these mistakes :smile:)

I think just using rasterio for now makes sense then, since we're also using it for warping bboxes if needed (though that's a bit uncertain, see #7)

**Comment by vincentsarago** [comment]
> Thanks (I'm new to geospatial, so expect many of these mistakes 😄)

Don't worry, this is not a `mistake`
